name: depolying my index.html
on: [push]


jobs:
  build:
    name: install ubuntu
    runs-on: ubuntu-latest
    name: deploying index.html to surge
    steps:
      - uses: actions/checkout@v2
      - name: installing Node.js  ob ubuntu
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: installaling Surge globally
        run: npm install -g surge
      - name: running surge 
        run: surge ./ bootcamp_wajahat.surge.sh --token ${{ secrets.SURGE_TOKEN }}

